export interface Env {
    DIRECTUS_API_LINKS_ENDPOINT: string;
    DIRECTUS_API_EXTERNAL_LOGS_ENDPOINT: string;
    DIRECTUS_API_TOKEN: string;
    CLOUDFLARE_ACCESS_CLIENT_ID: string;
    CLOUDFLARE_ACCESS_CLIENT_SECRET: string;
    EMBEDDED_FALLBACK_URL: string;
}
